#!/bin/bash

service::config_set() {
  config::check_or_set $@ $SERVICE_CONFIG
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service][gitlab]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  service::config_set SERVICE_GITLAB_COMPANY text
  service::config_set SERVICE_GITLAB_HTTP_PORT text
  service::config_set SERVICE_GITLAB_ROOT_PASSWORD text

  # @TODO cannot input :
  service::config_set SERVICE_GITLAB_ROOT_URL text
}

check $@
