version: '3.7'

services:
  gitlab:
    restart: always
    image: whatwewant/gitlab:${SERVICE_GITLAB_IMAGE_VERSION}
    # host: tgit.shushu.work
    ports:
      - 0.0.0.0:${SERVICE_GITLAB_HTTP_PORT}:80
      # - 0.0.0.0:${SERVICE_GITLAB_SSH_PORT}:22
    # hostname: gitlab.example.com
    hostname: gitlab # visit: http://gitlab
    volumes:
      - ${SERVICE_CONFIGS}/gitlab:/etc/gitlab
      - ${SERVICE_DATA}/gitlab:/var/opt/gitlab
      - ${SERVICE_LOGS}/gitlab:/var/log/gitlab
      # - type: bind
      #   source: /var/run/docker.sock
      #   target: /var/run/docker.sock
    environment:
      GITLAB_ROOT_PASSWORD: ${SERVICE_GITLAB_ROOT_PASSWORD}
      # GITLAB_HOST: ${SERVICE_GITLAB_ROOT_URL}
      # EXTERNAL_URL: ${SERVICE_GITLAB_ROOT_URL}
      # GITLAB_OMNIBUS_CONFIG: "external_url '${SERVICE_GITLAB_ROOT_URL}'"
      GITLAB_ROOT_URL: ${SERVICE_GITLAB_ROOT_URL}
      #
      DOREAMON_CLIENT_ID: $SERVICE_GITLAB_DOREAMON_CLIENT_ID
      DOREAMON_CLIENT_SECRET: $SERVICE_GITLAB_DOREAMON_CLIENT_SECRET
      #
      DOREAMON_LOGIN_BUTTON_NAME: $SERVICE_GITLAB_DOREAMON_LOGIN_BUTTON_NAME

networks:
  default:
    external: true
    name: compose-ingress
